server:
  port: 8888

spring:
  kafka:
    bootstrap-servers: "127.0.0.1:29092"
    consumer:
      group-id: my-group
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "com.learning.cdc.debezium.db.kafka.impl.deserializer.ProductMessageDeserializer"
      auto-offset-reset: earliest